<a href="https://colab.research.google.com/github/CamiloLezcanoUdea/clases_cinecia_de_datos_20252/blob/master/numpy_20252.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
## Numpy

import numpy as np

# 1. crear un arreglo

# 1.1 desde listas

arr = np.array([1,2,3,4])
print("Arreglo desde listas: ")
print(arr)
print("\n")

# 1.2 desde matrices

mat = np.array([[1,2,3],[4,5,6]])
print("Matriz: ")
print(mat)
print("\n")

# 1.3 con rangos

range = np.arange(0,10,2)
print("Arreglo con rangos: ")
print(range)
print("\n")

# 1.4 arreclo con ceros y unos

zeros = np.zeros((3,3))
ones = np.ones((2,4))
print("Arreglo de ceros: ")
print(zeros)
print("\n")
print("Arreglo de unos: ")
print(ones)
print("\n")

# 1.5 aleatorios

random = np.random.rand(3,3)
random_int = np.random.randint(1,100,(3,3))

print("Arreglo aleatorio: ")
print(random)
print("\n")
print("Arreglo aleatorio de enteros: ")
print(random_int)


Arreglo desde listas: 
[1 2 3 4]


Matriz: 
[[1 2 3]
 [4 5 6]]


Arreglo con rangos: 
[0 2 4 6 8]


Arreglo de ceros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Arreglo de unos: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Arreglo aleatorio: 
[[0.89817531 0.7592247  0.32200379]
 [0.96304819 0.07847749 0.69593507]
 [0.76341676 0.01393755 0.267344  ]]


Arreglo aleatorio de enteros: 
[[18  4  2]
 [94 35 97]
 [50 61 21]]


In [7]:
# 2. Propiedades de un arreglo

# 2.1 numero de dimensiones

ndim = mat.ndim
print("Numero de dimensiones: ")
print(ndim)
print("\n")

# 2.2 forma

shape = mat.shape
print("Forma: ")
print(shape)
print("\n")

# 2.3 numero de elementos

size = mat.size
print("Numero de elementos: ")
print(size)
print("\n")

# 2.4 tipo de dato

dtype = mat.dtype
print("Tipo de dato: ")
print(dtype)
print("\n")

Numero de dimensiones: 
2


Forma: 
(2, 3)


Numero de elementos: 
6


Tipo de dato: 
int64




In [13]:
# 3 Indexación y slicing

# arreglo

arr2 = np.array([10,20,30,40,50])
index = arr2[3]
index_range = arr2[0:3]
slicing = arr2[::-1]

print("indice: ")
print(index)
print("indice con rango: ")
print(index_range)
print("slicing: ")
print(slicing)
print("\n")


# Matrices

mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
index2 = mat2[1,2]
index_column = mat2[:,0]
index_row = mat2[1,:]
submatriz = mat2[0:2,1:3]

print("matriz: ")
print(mat2)
print("indice: ")
print(index2)
print("indice columna: ")
print(index_column)
print("indice fila: ")
print(index_row)
print("submatriz: ")
print(submatriz)

indice: 
40
indice con rango: 
[10 20 30]
slicing: 
[50 40 30 20 10]


matriz: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
indice: 
6
indice columna: 
[1 4 7]
indice fila: 
[4 5 6]
submatriz: 
[[2 3]
 [5 6]]


In [16]:
# 4. opreaciones matematicas

sum = arr + 5
print("suma: ")
print(sum)

mult = arr * 2
print("multiplicacion: ")
print(mult)

div = arr / 3
print("division: ")
print(div)

exp = arr ** 2
print("exponente: ")
print(exp)

# entre arreglos

a = np.array([1,2,3])
b = np.array([4,5,6])

sum_arr = a + b
mult_arr = a * b
div_arr = a / b
exp_arr = a ** b

print("suma de arreglos: ")
print(sum_arr)
print("multiplicacion de arreglos: ")
print(mult_arr)
print("division de arreglos: ")
print(div_arr)
print("exponente de arreglos: ")
print(exp_arr)

suma: 
[6 7 8 9]
multiplicacion: 
[2 4 6 8]
division: 
[0.33333333 0.66666667 1.         1.33333333]
exponente: 
[ 1  4  9 16]
suma de arreglos: 
[5 7 9]
multiplicacion de arreglos: 
[ 4 10 18]
division de arreglos: 
[0.25 0.4  0.5 ]
exponente de arreglos: 
[  1  32 729]


In [17]:
# 5. Funciones

sqrt = np.sqrt(arr)
print("Raiz cuadrada: ")
print(sqrt)

mean = np.mean(arr)
print("Media: ")
print(mean)

sumx = np.sum(arr)
print("Suma: ")
print(sumx)

max = np.max(arr)
print("Maximo: ")
print(max)

min = np.min(arr)
print("Minimo: ")
print(min)

std = np.std(arr)
print("desviacion estandar: ")
print(std)

Raiz cuadrada: 
[1.         1.41421356 1.73205081 2.        ]
Media: 
2.5
Suma: 
10
Maximo: 
4
Minimo: 
1
desviacion estandar: 
1.118033988749895
